post http://localhost:3000/register
Content-Type: application/json

{
    "username":"AD",
    "password":"1234567",
    "name":"Adlinaa"
}

###

Post http://localhost:3000/login
Content-Type: application/json

{
    "username":"AD",
    "password":"1234567"
}

###